### ISSUE TITLE
Can't compile library with swift 5

### ISSUE THREAD

**Issue by NancyKashyap-Stride** [ServicePattern/MobileAPI_IOS#22]
I have imported library in my app and using swift 5 but I am getting compilation errors and can't run the code.

**Comment by ALobastov** [comment]
Please provide the xCode log showing the errors.

**Comment by NancyKashyap-Stride** [comment]
Attached xcode error screenshot. It can be easily reproduce in sample app that is provided running with swift 5.

<img width="1440" alt="Screen Shot 2021-03-30 at 3 05 28 pm" src="https://user-images.githubusercontent.com/41280808/112932470-ade52000-9169-11eb-9407-3f5dac6774f4.png">

**Comment by ALobastov** [comment]
Fixed
