### ISSUE TITLE
CloseCase api error

### ISSUE THREAD

**Issue by NancyKashyap-Stride** [ServicePattern/MobileAPI_IOS#32]
Creating seperate issue related to close case api error.

When I try to close the case, api is sending error. Method:- closeCase
Error: BPMobileMessaging.ContactCenterError.chatSessionCaseNotSpecified.

**Comment by ALobastov** [comment]
Please attach full logs as requested before.

**Comment by NancyKashyap-Stride** [comment]
Please find attached xcode logs.

[Close_case.zip](https://github.com/ServicePattern/MobileAPI_IOS/files/6301187/Close_case.zip)

**Comment by ALobastov** [comment]
Not a defect - the designed behavior. The scenario which handles chat session must determine which CRM Case the session is associated with and specifically enable the API to retrieve case history or close the case. Once done, the client application will receive chatSessionCaseSet event which indicates that case history is available and case can be closed (the getCaseHistory and closeCase methods can be called). Attempts to call these methods before case is set will result in error 406 - this is clearly documented in the getCaseHistory() method description.

Attached logs confirm that a case has not been set (there is no chatSessionCaseSet event).
