### ISSUE TITLE
App is not receiving chatSessionCaseSet event

### ISSUE THREAD

**Issue by NancyKashyap-Stride** [ServicePattern/MobileAPI_IOS#35]
Case is created by agent and confirmed the case id #1004 but app is not receiving events in this case. Please find attached logs
[ChatSessionCaseSet.zip](https://github.com/ServicePattern/MobileAPI_IOS/files/6314888/ChatSessionCaseSet.zip)

**Comment by ALobastov** [comment]
Should be the scenario issue (scenario is maintained by TTec). It is not enough to just create a case; scenario must also assign the newly created (or found) case to the session. This is done with the Set Case scenario block (do not forget to check the "Allow API..." checkbox.

**Comment by NancyKashyap-Stride** [comment]
Please find attached scenario.

[app_MobileApp_Chat_03162021.zip](https://github.com/ServicePattern/MobileAPI_IOS/files/6315816/app_MobileApp_Chat_03162021.zip)
