### ISSUE TITLE
Case not found

### ISSUE THREAD

**Issue by NancyKashyap-Stride** [ServicePattern/MobileAPI_IOS#38]
Please find attached scenario:
When app is getting message for existing case id and replying to yes returns 'No case found'.

[app_MobileScenario(1).zip](https://github.com/ServicePattern/MobileAPI_IOS/files/6402430/app_MobileScenario.1.zip)
![IMG_0262](https://user-images.githubusercontent.com/41280808/116635940-6f7a9500-a9a3-11eb-98e1-f3a00e5dc979.PNG)
![IMG_0261](https://user-images.githubusercontent.com/41280808/116635947-72758580-a9a3-11eb-8e6d-49a1597e569e.PNG)

**Comment by ALobastov** [comment]
Scenarios are TTec responsibility; not API/Library issue. TTec is supposed to deploy the overall solution which would integration the system with existing databases (if any). GitHub is for SDK development/issues only.
