### ISSUE TITLE
requestChat api error

### ISSUE THREAD

**Issue by NancyKashyap-Stride** [ServicePattern/MobileAPI_IOS#42]
Please find attached logs.

1. Check availability api is giving error - Failed to check availability: badStatusCode(statusCode: 502, nil)
2. Attached logs also have request chat method which is returning json decoding issue.

Please note: To get this log for request chat api method - app is not restricting call for requestChat method if checkAvailability api is giving error. This is just to pass on logs so that you can check both api calls errors.

[RequestChat.zip](https://github.com/ServicePattern/MobileAPI_IOS/files/6706051/RequestChat.zip)

**Comment by ALobastov** [comment]
BPCC server never responds with HTTP code 502, so the issue should be in the infrastructure between mobile app and BPCC server. Most probably Nginx.

JSON decoding issue is a consequence - error 502 did not return any payload.

Best regards,

Alex

**Comment by ALobastov** [comment]
Has the issue been resolved already?

**Comment by NancyKashyap-Stride** [comment]
Looks like after updating scenarios from ttec, app is not getting 502 error now.
